services:
  go:
    container_name: html_generator_hana
    platform: linux/x86_64
    hostname: localhost
    tty: true
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    volumes:
      - ./app:/go/src/app
